### ISSUE TITLE
"Loading rooms..." over "You haven't joined any rooms yet" (same for DMs)

### ISSUE THREAD

**Issue by foxyseta** [ulyssa/iamb#185] opened 2023-12-09 15:36 UTC
When loading my rooms, iamb displays a "You haven't joined any rooms yet". I'd say this message is appropriate for users who indeed have not joined any rooms yet, but not for the "loading" scenario.

Same for the "No direct messages yet!" message when loading DMs.

**Comment by benjajaja** [comment] 2024-01-06 14:06
duplicate of #145

**Closed** 2024-01-06 20:26 UTC
